### ISSUE TITLE
Calendar UI

### ISSUE THREAD

**Issue by putriz** [WhenIsBest/whenisbest#13]
Create the UI for the calendar, which hopefully will receive information from Google Calendar. This goes on the homepage and the page for each group when clicked.

**Comment by putriz** [comment]
Some resources that I have found which may be helpful:
https://richonrails.com/articles/building-a-basic-calendar-in-ruby-on-rails
http://jagadeeshror.blogspot.com/2012/03/event-calendar.html

**Comment by harrij15** [comment]
^Awks, never saw these
