### ISSUE TITLE
Incorrect date for "today" on the calendar

### ISSUE THREAD

**Issue by putriz** [WhenIsBest/whenisbest#34]
The calendar highlights today's date on the calendar, but it seems to highlight the day after instead.
For example, 
![screenshot 124](https://cloud.githubusercontent.com/assets/16448052/20586345/256d31bc-b1d1-11e6-8349-d96c9b5fd48f.png)
in the picture above, today's real date is currently Nov 23, but Nov 24 was highlighted as "today".

**Comment by harrij15** [comment]
...huh okay

**Comment by harrij15** [comment]
What exactly are you using to highlight "today"? or is it built-in?

**Comment by putriz** [comment]
It's from their code. I'm not exactly sure where they do it...

**Comment by putriz** [comment]
In simple_calendar.scss though they have
    .today {
        background: #FFFFC0;
    }

**Comment by harrij15** [comment]
would the ".today" refer to a variable in the code?

**Comment by harrij15** [comment]
Actually, I think I just found it in the code.

**Comment by harrij15** [comment]
Oh, I forgot to say that this is occurring because the time zone is wrong
