### ISSUE TITLE
Display of events and their duration on calendar is incorrect

### ISSUE THREAD

**Issue by putriz** [WhenIsBest/whenisbest#78]
![screenshot 240](https://cloud.githubusercontent.com/assets/16448052/24766868/fc8d33f6-1aca-11e7-905e-8d6427729a64.png)

In the above example, the event "Sleeping" was set from 12:00 AM 12:00 pm (12 hours), however the duration on the calendar shows that it goes from 12:00 AM to 12:00 AM (24 Hours), completely skipping the 12 PM stop time.

**Comment by harrij15** [comment]
Resolved in the pull request

https://gyazo.com/3d071f885b102eeb6be97aad8febd8c3
